CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE administradores (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    usuario character varying(100) NOT NULL,
    contrasena_hash character varying(200) NOT NULL,
    activo boolean NOT NULL,
    areas text[] NOT NULL,
    CONSTRAINT pk_administradores PRIMARY KEY (id)
);

CREATE TABLE auditoria (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    fecha_hora timestamp with time zone NOT NULL,
    usuario character varying(200) NOT NULL,
    modulo character varying(100) NOT NULL,
    accion character varying(20) NOT NULL,
    entidad character varying(300) NOT NULL,
    detalle_antes text,
    detalle_despues text,
    CONSTRAINT pk_auditoria PRIMARY KEY (id)
);

CREATE TABLE cierres_caja (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    estado character varying(20) NOT NULL,
    fecha_apertura timestamp with time zone NOT NULL,
    fondo_inicial numeric(18,2) NOT NULL,
    notas_apertura text,
    fecha_cierre timestamp with time zone,
    ventas_del_dia numeric(18,2) NOT NULL,
    gastos_del_dia numeric(18,2) NOT NULL,
    notas_cierre text,
    CONSTRAINT pk_cierres_caja PRIMARY KEY (id)
);

CREATE TABLE dispositivos_operaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    token character varying(100) NOT NULL,
    estacion character varying(20) NOT NULL,
    nombre character varying(200) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    CONSTRAINT pk_dispositivos_operaciones PRIMARY KEY (id)
);

CREATE TABLE empleados (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(200) NOT NULL,
    clave_hash character varying(200) NOT NULL,
    rol character varying(20) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT pk_empleados PRIMARY KEY (id)
);

CREATE TABLE finanzas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    monto numeric(18,2) NOT NULL,
    tipo character varying(20) NOT NULL,
    categoria character varying(100) NOT NULL,
    descripcion character varying(500) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    CONSTRAINT pk_finanzas PRIMARY KEY (id)
);

CREATE TABLE insumos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(200) NOT NULL,
    unidad character varying(20) NOT NULL,
    stock_actual numeric(18,4) NOT NULL,
    stock_minimo numeric(18,4) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT pk_insumos PRIMARY KEY (id)
);

CREATE TABLE items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    platillo character varying(200) NOT NULL,
    categoria character varying(100) NOT NULL,
    precio numeric(18,2) NOT NULL,
    ingredientes text NOT NULL,
    descripcion text NOT NULL,
    base text NOT NULL,
    activo boolean NOT NULL,
    agotado boolean NOT NULL,
    imagen_url text,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE opiniones (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    item_id integer,
    nombre_cliente character varying(200),
    comentario character varying(1000) NOT NULL,
    calificacion numeric(3,1) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    registrado_por character varying(200) NOT NULL,
    CONSTRAINT pk_opiniones PRIMARY KEY (id)
);

CREATE TABLE pedidos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    mesa character varying(50) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    CONSTRAINT pk_pedidos PRIMARY KEY (id)
);

CREATE TABLE promociones (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    titulo character varying(200) NOT NULL,
    descripcion text,
    imagen_url text,
    tipo_descuento character varying(20) NOT NULL,
    valor_descuento numeric(18,2),
    item_ids integer[] NOT NULL,
    activa boolean NOT NULL,
    fecha_inicio timestamp with time zone,
    fecha_fin timestamp with time zone,
    CONSTRAINT pk_promociones PRIMARY KEY (id)
);

CREATE TABLE recetas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    item_id integer NOT NULL,
    nombre_receta character varying(200) NOT NULL,
    rendimiento integer NOT NULL,
    unidad_rendimiento character varying(50) NOT NULL,
    notas text,
    fecha_actualizacion timestamp with time zone NOT NULL,
    CONSTRAINT pk_recetas PRIMARY KEY (id)
);

CREATE TABLE supervisor_clave (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clave_hash character varying(200) NOT NULL,
    CONSTRAINT pk_supervisor_clave PRIMARY KEY (id)
);

CREATE TABLE pedido_items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    item_id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(18,2) NOT NULL,
    pedido_id integer NOT NULL,
    CONSTRAINT pk_pedido_items PRIMARY KEY (id),
    CONSTRAINT fk_pedido_items_pedidos_pedido_id FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE CASCADE
);

CREATE TABLE receta_ingredientes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    insumo_id integer NOT NULL,
    nombre character varying(200) NOT NULL,
    cantidad numeric(18,4) NOT NULL,
    unidad character varying(20) NOT NULL,
    costo_unitario numeric(18,4) NOT NULL,
    receta_id integer NOT NULL,
    CONSTRAINT pk_receta_ingredientes PRIMARY KEY (id),
    CONSTRAINT fk_receta_ingredientes_recetas_receta_id FOREIGN KEY (receta_id) REFERENCES recetas (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_administradores_usuario ON administradores (usuario);

CREATE UNIQUE INDEX ix_dispositivos_operaciones_token ON dispositivos_operaciones (token);

CREATE INDEX ix_pedido_items_pedido_id ON pedido_items (pedido_id);

CREATE INDEX ix_receta_ingredientes_receta_id ON receta_ingredientes (receta_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260730174131_InitialCreate', '10.0.1');

COMMIT;

