<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Include="ADRs\ARD-04-Joaquin-Uriona.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProyectoJo.Application\ProyectoJo.Application.csproj" />
    <ProjectReference Include="..\ProyectoJo.Domain\ProyectoJo.Domain.csproj" />
    <ProjectReference Include="..\ProyectoJo.Infrastructure\ProyectoJo.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Views\nosotros\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
